DROP TABLE IF EXISTS Prestito
DROP TABLE IF EXISTS Libro
DROP TABLE IF EXISTS Utente

CREATE TABLE Utente (
    utenteID INT PRIMARY KEY IDENTITY(1,1),
    nome NVARCHAR(100) NOT NULL,
    cognome NVARCHAR(100) NOT NULL,
    mail NVARCHAR(100),
	codiceUtente VARCHAR(50) NOT NULL UNIQUE,
	deleted DATETIME						-- SOFT DELETE
);
CREATE TABLE Libro (
    libroID INT PRIMARY KEY IDENTITY(1,1),
    titolo NVARCHAR(100) NOT NULL,
    annoPub INT NOT NULL,
    isDisp BIT DEFAULT 1,
	isbn VARCHAR(50) NOT NULL UNIQUE,
	deleted DATETIME
);
CREATE TABLE Prestito (
    prestitoID INT PRIMARY KEY IDENTITY(1,1),
    dataPres DATETIME DEFAULT CURRENT_TIMESTAMP,
    dataRit DATETIME,
	utenteRIF INT NOT NULL,
	libroRIF INT NOT NULL,
	codicePres VARCHAR(50) NOT NULL UNIQUE,
	FOREIGN KEY (utenteRIF) REFERENCES Utente(utenteID),
	FOREIGN KEY (libroRIF) REFERENCES Libro(libroID),
	deleted DATETIME
);